{
 "title": "Rblib Flashblocks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Payloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Payloads Built",
   "type": "stat",
   "description": "Number of payload jobs that have produced a block payload successfully.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_rblib_payload_jobs_completed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions Count",
   "type": "stat",
   "description": "The total number of all transactions built across all payload jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_rblib_payload_tx_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gas Built",
   "type": "stat",
   "description": "The sum of all gas consumed by all transactions built across all payload jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_rblib_payload_gas_used_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blob Gas Built",
   "type": "stat",
   "description": "Total blob gas used by all blob transactions in all produced payloads.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_rblib_payload_blob_gas_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fees",
   "type": "stat",
   "description": "Total fees accumulated by all produced payloads.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_rblib_payload_fees_total / 1e18",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Payload Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_rblib_payload_jobs_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions Per Payload",
   "type": "timeseries",
   "description": "Number of transactions in a produced payload.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "reth_rblib_payload_tx_count_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Jobs Success Rate",
   "type": "timeseries",
   "description": "Percentage of Payload Jobs that ended in successfully built payload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_rblib_payload_jobs_completed / reth_rblib_payload_jobs_started",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Job Duration",
   "type": "timeseries",
   "description": "Duration of a payload job from start to completion or failure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_rblib_payload_job_duration{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas per Payload",
   "type": "timeseries",
   "description": "Amount of gas used by transactions in a produced payload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "reth_rblib_payload_gas_used_histogram{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fees per Payload (Gwei)",
   "type": "timeseries",
   "description": "Fees paid by transactions in produced payloads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "reth_rblib_payload_fees_histogram{quantile=\"0.95\"} / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload Gas Utilization",
   "type": "timeseries",
   "description": "The percentage of gas utilized by transactions in a produced payload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_rblib_payload_gas_utilized{quantile=\"0.95\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}